services: 
    server: 
        container_name: Django
        build: ./server
        command: bash -c "
            python manage.py runserver 0.0.0.0:8000"
        volumes: 
            -.:/server
        ports:
            8000:8000
        