# Generated by Django 3.0.7 on 2020-07-09 15:54

import config.case.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default='True')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(default='', max_length=255)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, config.case.mixins.FromCamelCase, config.case.mixins.ToCamelCase),
        ),
    ]
